const lesson112 = {
   "joke": "шутка, шутить",
   "pretend": "притворяться",
   "envelope": "конверт",
   "stamp": "печать, почтовая марка",
   "leave out": "пропускать",
   "postcode": "Почтовый индекс",
   "naturally": "непринужденно, естественно",
   "recent": "последний, недавний",
   "so-so": "так себе",
   "mate": "друг",
   "housemate": "сосед по дому",
   "flatmate": "сосед по квартире",
   "classmate": "одноклассник",
   "workmate": "сотрудник",
   "to look forward to": "с нетерпением ожидать",
   "let me see": "дайте подумать",
   "chance": "шанс",
   "dismiss": "увольнять",
   "jungle": "джунгли",
   "fifty-fifty": "пятьдесят на пятьдесят",
   "take a chance": "рискнуть",
   "whistle": "свистеть",
   "hunt": "охотиться",
   "deed": "поступок",
   "grease": "Смазка",
   "scissors": "ножницы",
   "take control": "брать управление",
   "lose control": "терять управление",
   "due": "надлежащий, должный",
   "due to": "из-за",
   "grandmother": "бабушка",
   "grandfather": "дедушка",
   "great-grandmother": "прабабушка",
   "great-grandfather": "прадедушка",
   "mostly": "В основном",
   "totally": "абсолютно",
   "sentence": "приговаривать"
};

const lesson113 = {
   "discuss": "обсуждать",
   "discussion": "обсуждение",
   "argue": "спорить",
   "argument": "спор",
   "quarrel": "ссориться, ссора",
   "anger": "гнев",
   "reason": "излагать мотивы, рассуждать, аргументировать",
   "regular ": "регулярный, систематический, постоянный",
   "do something about": "предпринимать что-то относительно",
   "blow up": "взрывать",
   "dust": "пыль",
   "powder": "порошок",
   "collect": "собираться, собирать",
   "face powder": "пудра для лица",
   "meeting": "собрание",
   "football match": "футбольный матч",
   "Red Cross": "Красный Крест",
   "furniture": "мебель",
   "furnish": "обставлять мебелью",
   "available": "доступный",
   "human being": "человек",
   "artificial": "искуственный",
   "kiss": "целовать",
   "rush": "устремляться, напряженный (the rush hour - час-пик)",
   "hero": "герой"
};

const lesson114 = {
   "dish": "блюдо",
   "serve": "подавать",
   "to be for (or against) something": "быть за что-то (или против чего-то)",
   "arms": "оружие",
   "fox": "лисица",
   "fox hunting": "охота на лис",
   "seize": "схватить",
   "handbag": "сумочка",
   "break out": "вспыхнуть, разразиться",
   "wage": "оплата труда",
   "salary": "оклад, зарплата",
   "payment": "платеж",
   "profession": "профессия",
   "non-professional": "непрофессиональный",
   "steady": "постоянный, твердый",
   "seasonal": "сезонный",
   "seaside": "морское побережье",
   "painter": "художник",
   "pianist": "пианист",
   "surgeon": "хирург",
   "leaf": "лист",
   "loat": "буханка",
   "shelf": "полка",
   "cliff": "утес",
   "deer": "олень",
   "wood": "лес",
   "mention": "упоминать",
   "tell off": "отчитывать",
   "partner": "партнер",
   "insist": "настаивать",
   "board": "доска, совет (директоров), правление, питание",
   "floorboard": "половица",
   "noticeboard": "доска объявлений",
   "blackboard": "школьная доска",
   "deck": "палуба",
   "port": "порт",
   "director": "директор"
};

const lesson115 = {
   "timetable": "расписание",
   "schedule": "расписание",
   "account": "перечень, рассказ, счет, учет",
   "greedy": "жадный",
   "satisfied": "удовлетворенный",
   "crop": "сельскохозяйственная культура",
   "differ": "отличаться",
   "private": "частный",
   "what": "который, кто",
   "whom": "кто, кого",
   "whose": "чей",
   "search": "искать, обыскивать",
   "support": "поддерживать",
   "religious": "религиозный",
};

const lesson116 = {
   "declare": "заявлять, объявлять, оглашать",
   "red-handed": "с пoличным",
   "innocent": "невиновный",
   "upper": "высший",
   "middle": "средний",
   "working": "рабочий",
   "class": "класс",
   "society": "общество",
   "aristocracy": "аристократия",
   "industrialist": "промышленник",
   "case": "регистр (клавиатуры)",
   "lower": "нижний",
   "raise": "поднимать, растить, выращивать, воздвигать",
   "to be excused": "получить разрешение, быть отпущенным",
   "monument": "монумент, памятник",
   "honour": "честь",
   "statue": "статуя",
   "transitive": "переходный",
   "respect": "уважение",
   "scorn": "презрение",
   "worthy": "достойный",
   "term": "четверты / семестр",
   "worship": "поклоняться",
   "cattle": "крупный рогатый скот",
   "cowboy": "ковбой",
   "harvest": "урожай",
   "mother-in-law": "теща, свекровь",
   "father-in-law": "тесть, свекор",
   "rail": "рельс",
   "railing": "ограждение, перила",
   "run": "двигаться",
   "protection": "защита",
   "balcony": "балкон",
};

const lesson117 = {
   "knowledge": "знание",
   "progress": "прогресс",
   "item": "предмет",
   "encyclopedia": "энциклопедия",
   "mass": "масса",
   "advantage": "преимущество",
   "disadvantage": "недостаток",
   "mass-production": "массовое производство",
   "production": "производство",
   "product": "продукт",
   "identical": "идентичный",
   "quality": "качество",
   "pick up": "поднимать, заезжать, подцепить",
   "date": "свидание",
   "vocabulary": "лексикон, словарный запас",
   "prevent": "предотвращать",
   "drum": "барабан, барабанить, циллиндрический контейнер",
   "harbour": "гавань",
   "port": "порт",
   "nosey": "любопытный",
   "masculine": "мужской род",
   "feminine": "женский род",
   "god": "бог",
   "goddess": "богиня",
   "prince": "принц",
   "princess": "принцесса",
   "nephew": "племянник",
   "niece": "племянница",
   "landlord": "домовладелец, арендодатель, землевладелец",
   "landlady": "домовладелица",
   "widower": "вдовец",
   "widow": "вдова",
   "event": "событие",
   "eventful": "насыщенный событиями",
   "uneventful": "без особенных проишествий, событий; непримечательный",
   "concern": "касаться",
   "celebrate": "праздновать",
   "celebration": "празднование",
   "New Year's Eve": "канун Нового Года",
   "up to date": "актуальный, действительный",
   "out of date": "просроченный",
   "essential": "необходимый, важный",
};

const lesson118 = {
   "article": "артикль",
   "countable": "исчисляемый",
   "uncountable": "неисчисляемый",
   "worm": "червь",
   "silkworm": "шелковичный червь",
   "silk": "шелк",
   "limb": "конечность",
   "poison": "яд",
   "cave": "пещера",
   "bat": "летучая мышь",
   "deserve": "заслуживать",
   "frequent (verb)": "посещать",
   "frequent (adjective)": "частый",
   "frequently (adverb)": "часто",
   "attract": "привлекать",
   "attention": "внимание",
   "attraction": "достопримечательность",
   "attractive": "привлекательный",
   "good-looking": "симпатичный",
   "the rest": "остальные",
   "miserable": "жалкий, мерзкий",
   "emotion": "эмоция",
   "emotional": "эмоциональный"
};

const lesson119 = {
   "firstly": "во-первых",
   "secondly": "во-вторых",
   "head teacher": "директор школы",
   "study": "кабинет",
   "vote": "голосовать",
   "nurse": "ухаживать за больным, няньчить",
   "nursery": "детский сад",
   "unemployment": "безработица",
   "take off": "взлетать",
   "land": "приземляться",
   "seat belt": "ремень безопасности",
   "practice": "практика",
   "theory": "теория",
   "practical": "дельный, практичный",
   "take into account": "принимать во внимание",
   "set up": "организовать",
   "nature": "натура",
   "human nature": "человеческая натура",
   "compete": "соревноваться",
   "competition": "соревнование",
   "energy": "энергия",
   "efficient": "эффективный",
   "suit": "идти, подходить",
   "suitable": "подходящий",
   "effect": "последствия, воздействие, впечатление",
   "perfect": "совершенный",
   "to go up to": "подходить к",
   "sunshine": "солнечный свет"
};

const lesson120 = {
   "polish": "начищать",
   "ability": "способность",
   "expense": "расход",
   "postpone": "откладывать на другое время",
   "stress": "стресс",
   "stressful": "напряженный",
   "afterwards": "впоследствии",
   "first of all": "прежде всего",
   "attend": "посещать, обслуживать, быть внимательным",
   "shopkeeper": "владелец магазина",
   "move": "трогать, волновать; вызывать (какие-л, чувства, эмоции)",
   "tear": "слеза",
   "pass": "передавать",
   "spoil - spoilt - spoilt": "портить - портил - испортил",
   "discipline": "дисциплина",
   "hunger": "голод",
   "share": "делиться, делить, акция"
};

const lesson121 = {
   "association": "ассоциация",
   "automobile": "автомобильный",
   "disturb": "беспокоить",
   "concentrate": "концентрироваться",
   "courage": "смелость",
   "virtue": "добродетель",
   "loyal": "верный, преданный",
   "loyalty": "верность",
   "companion": "спутник",
   "spirit": "дух, душа, настроение, алкогольный напиток",
   "spiritual": "духовный",
   "evil": "злой",
   "flow": "течь, поток",
   "festival": "фестиваль",
   "feast": "пир",
   "dare": "осмелиться, сметь",
   "challenge": "бросать вызов",
   "bring up": "воспитывать",
   "solve": "решать",
   "calculator": "калькулятор",
   "fix": "скрепить, назначить, повесить",
   "hammer": "молоток",
   "nail": "гвоздь",
   "fingernail": "ноготь",
   "criticize": "критиковать"
};

const lesson122 = {
   "yard": "двор",
   "courtyard": "двор",
   "enclose": "огораживать",
   "space": "пространство",
   "amuse": "веселить, развлекать",
   "comic": "комичный",
   "pass (the time)": "проводить (время)",
   "cards": "карты",
   "waiting room": "приемная",
   "amusement": "развлечение",
   "hobby": "хобби",
   "photography": "фотография",
   "order": "порядок",
   "pack": "собирать (чемодан)",
   "packed": "переполненный",
   "suitcase": "чемодан",
   "shorts": "шорты",
   "T-shirt": "футболка",
   "thorn": "шип",
   "rose": "роза",
   "afford": "позволять себе",
   "agreement": "сoглашение",
   "basket": "корзина",
   "trolley": "тележка",
   "nut": "орех",
   "regarding": "относительно",
   "material": "материал",
   "duvet": "стеганое пуховое одеяло",
   "cotton": "хлопок",
   "leather": "кожа",
   "convenience": "удобство, удобства",
   "convenient": "удобный",
   "inconvenient": "неудобный",
   "inconvenience": "неудобство",
   "dining room": "столовая",
   "sensitive": "чувствительный, чуткий, восприимчивый",
   "offend": "обидеть",
   "criticism": "критика",
   "thermometer": "термометр",
   "sensible": "разумный",
   "reasonable": "разумный",
   "shopping centre": "торговый центр",
   "balance": "балансировать, сходиться (о цифрах), остаток",
   "add up": "прибавлять",
   "bind - bound - bound": "связывать - связал - связал",
};

const lesson123 = {
   "note": "записка, замечать, нота",
   "note down": "записывать",
   "take notes": "вести заметки",
   "notebook": "записная книжка",
   "banknote": "банкнота",
   "key": "клавиша",
   "keyboard": "клавиатура",
   "armour": "доспехи",
   "spread": "распространять(ся)",
   "all over": "по всему",
   "fascinated": "пораженный",
   "scene": "место",
   "murderer": "убийца",
   "evidence": "улика, доказательство",
   "i.e. = id est = that is": "т.е. = то есть",
   "at first": "вначале",
   "accustomed": "привычный"
};

const lesson124 = {
   "benefit": "польза",
   "sake": "ради",
   "give up": "прекращать",
   "mixed up": "перепутанный",
   "humour": "юмор",
   "dress": "одежда",
   "master": "мастер, овладевать, усваивать",
   "masterpiece": "шедевр",
   "so": "поэтому, чтобы, итак",
   "so that": "так, чтобы",
   "so as to": "для того, чтобы",
   "and so on": "и так далее",
   "so many": "так много",
   "so far": "до сих пор",
   "so far as I know": "насколько я знаю",
   "praise": "хвалить, похвала",
   "loan": "заем",
   "furthermore": "кроме того",
   "moreover": "более того",
   "toe": "палец на ного",
   "personally": "лично",
   "conscious": "сознательный",
   "unconscious": "боссознательный",
   "self-conscious": "застенчивый",
   "patient": "пациент",
   "injection": "укол",
   "gathering": "собрание",
   "split": "раскалывать, лопнуть, разделить",
   "axe": "топор",
   "equally": "одинаково, поровну"
};

const lesson125 = {
   "Alps": "Альпы",
   "Andes": "Анды",
   "Himalayas": "Гималаи",
   "Netherlands": "Нидерланды",
   "present (noun +adj)": "подарок, настоящий, присутствующий",
   "present (verb)": "представлять, дарить",
   "swear - swore - sworn": "браниться - бранился - бранился",
   "lazy": "ленивый",
   "idle": "ленивый, незанятый, неиспользуемый",
   "play": "пьеса",
   "scene": "сцена",
   "verse": "стихи",
   "chorus": "припев",
   "pray": "молиться",
   "prayer": "молитва",
   "combine": "совмещать",
   "heads": "орел",
   "tails": "решка"
};

const lesson126 = {
   "extend": "тянуться, протягивать",
   "as far as": "до",
   "trust": "доверять, фонд",
   "dependent": "зависимый",
   "independent": "независимый",
   "punctual": "пунктуальный",
   "row": "грести",
   "oar": "весло",
   "wish": "хотеть (нереальное желание)",
   "ideal": "идеал",
   "theoretical": "теоретический",
   "actual": "фактический",
   "actually": "фактически",
   "check": "проверять",
   "change": "сдача",
   "log": "полено",
   "fireplace": "камин",
   "common sense": "здравый смысл",
   "tool": "инструмент",
   "bean": "боб"
};

const API = {
   vocabulary: {
      ...lesson112,
      ...lesson113,
      ...lesson114,
      ...lesson115,
      ...lesson116,
      ...lesson117,
      ...lesson118,
      ...lesson119,
      ...lesson120,
      ...lesson121,
      ...lesson122,
      ...lesson123,
      ...lesson124,
      ...lesson125,
      ...lesson126,
   },

   currentWord: {},

   isAnswered: false,

   init() {
      document.getElementById('submit').onclick = (event) => {
         if (API.isAnswered) {
            this.reset();
         } else {
            this.showTranslation();
         }
      };

      this.reset();
   },

   getRandomProperty() {
      const keys = Object.keys(this.vocabulary);
      const currentKey = keys[keys.length * Math.random() << 0]
      return {
         english: currentKey,
         russain: this.vocabulary[currentKey]
      };
   },

   reset() {
      delete this.vocabulary[this.currentWord.english]; // delete previous word
      this.currentWord = this.getRandomProperty();
      this.isAnswered = false;
      document.getElementById('english').innerText = this.currentWord.english;
      document.getElementById('russian').classList.add('empty');
      document.getElementById('russian').innerText = '';
   },

   showTranslation() {
      this.isAnswered = true;
      document.getElementById('russian').classList.remove('empty');
      document.getElementById('russian').innerText = this.currentWord.russain;
   }
};

API.init();
